Models/Ideas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace CsharpExam.Models
{
    public class Idea
    {
        [Key]
        public int IdeaId { get; set; }

        [Required]
        [MinLength(5, ErrorMessage = " Must be at least {1} characters!")]
        public string Body { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime UpdatedAt { get; set; } = DateTime.Now;

        public int UserId { get; set; }
        public string Alias { get; set; }
        // Navigation Property
        public User SubittedBy { get; set; }
        public List<Like> Likes { get; set; }

        public Idea (string alias, string body)
        {
            Alias = alias;
            Body = body;
        }

        public Idea ()
        {
            
        }
    }
}

Controllers/IdeasController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CsharpExam.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace CsharpExam.Controllers
{
    public class IdeasController : Controller
    {
        private BeltContext db;
        private int? uid {
            get {
                return HttpContext.Session.GetInt32("UserId");
            }
        }
        public IdeasController(BeltContext context)
        {
            db = context;
        }

        [HttpGet("/dashboard")]
        public IActionResult Dashboard()
        {
            if (uid == null)
            {
                return RedirectToAction("Index", "Home");
            }

            List<Idea> allIdeas = db.Ideas
            .Include(band => band.Likes)
            .ToList();

            return View(allIdeas);
        }

        [HttpGet("/New")]
        public IActionResult New()
        {
            if (uid == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost("/Create")]
        public IActionResult Create(Idea newIdea)
        {
            if (uid == null)
            {
                return RedirectToAction("Index", "Home");
            }
            if (ModelState.IsValid)
            {
                newIdea.UserId =(int)uid;
                db.Add(newIdea);
                db.SaveChanges();
                return RedirectToAction("Dashboard");
            }
            return View("New");
        }

        [HttpGet("/idea/{ideaId}/delete")]
        public IActionResult Delete(int ideaId)
        {
            Idea dbIdea = db.Ideas.FirstOrDefault(idea => idea.IdeaId == ideaId);
            db.Ideas.Remove(dbIdea);
            db.SaveChanges();

            return RedirectToAction("Dashboard");
        }
    }
}

Views/Ideas/Dashboard.cshtml
@model List<Idea>

<partial name="_Links"></partial>

<h2 class="text-center">All Ideas</h2>

@foreach (Idea ideas in Model)
{
    <div class="card mx-auto text-center mb-3 w-50">

        <div class="card-body">
            <h6 class="card-subtitle mb-2 text-muted">
                @ideas.Alias
            </h6>
            <p class="card-text">
                @ideas.Body
            </p>
            <a asp-action="Details" asp-controller="Posts" asp-route-id="@ideas.IdeaId">Details</a>
            <a class="text-danger" href="/idea/@ideas.IdeaId/delete">Delete</a>
            <div class="text-right">
                @* <a asp-controller="Ideas" asp-action="Delete" asp-route-bandId="@Model.ideaId" class="btn btn-danger">Delete</a> *@
            </div>
        </div>
    </div>
}

Views/Ideas/New.cshtml
@model Idea

<div class="container mt-4">
    <form asp-action="Create" asp-controller="Ideas" method="POST">
        <h3>
            Hi!
        </h3>
    
        </div>
        <div class="form-group row">
            <label asp-for="Body" class="col-sm-2 col-form-label">
                <span asp-validation-for="Body" class="text-danger font-weight-bold"></span>
            </label>
            <div class="col-sm-10">
                <textarea asp-for="Body" class="form-control" rows="10" placeholder="Post something witty here..."></textarea>
            </div>
        </div>

        <div class="text-right">
            <a asp-controller="Ideas" asp-action="Dashboard" class="btn btn-primary">Cancel</a>
            <button class="btn btn-success">Add Idea!</button>
        </div>
    </form>
</div>

Views/Ideas/_Links.cshtml
<ul class="nav ml-4">
  <li class="nav-item rounded-right">
    <a asp-controller="Ideas" asp-action="Dashboard" class="nav-link">Dashboard</a>
  </li>
  <li class="nav-item rounded-right">
    <a asp-controller="Ideas" asp-action="New" class="nav-link">New Idea</a>
  </li>
  <li class="nav-item rounded-right">
    <a asp-controller="Home" asp-action="Details" class="nav-link">User Details</a>
  </li>
  <li class="nav-item rounded-right">
    <a asp-controller="Home" asp-action="Logout" class="nav-link">Logout</a>
  </li>
</ul>